### ISSUE TITLE
Is this going to be the new "official Mesen/Mesen-S"?

### ISSUE THREAD

**Issue by SeanRamey** [NovaSquirrel/Mesen-SX#36]
So, I had an issue with Mesen on Arch Linux where it wasn't saving my controller input settings, and I decided to open an issue on the github. Then I noticed that it was archived, and looked into SourMesen leaving development of these projects, and found these new forks.

So, is this the mostly agreed upon consolidated Mesen/Mesen-S? If so, I would recommend a slight name change, and a new package on the AUR. I hope development can continue without too many issues.

**Comment by NovaSquirrel** [comment]
That sounds like #34 potentially?

And yeah the intention of my forks (aside from adding features I need for debugging) was to try to consolidate all the development into one place, instead of having a bunch of different forks with different features like what happened with FCE Ultra before FCEUX happened. I'm not currently actively working on the code but I have been merging in pull requests.

I do agree it needs some sort of name to differentiate it but I'm not sure what to call it instead.

**Comment by Eggo-dotcom** [comment]
is this dead? Im running the latest build of mesen-s from appveyor DevWin-0.4.0.66 and it runs things very nicely. Its my #1 emulator. Kinda sad to see it die.

**Comment by NovaSquirrel** [comment]
I don't think anyone is actively working on it right now at least

**Comment by Eggo-dotcom** [comment]
That is too bad. This emulator got good fast and was killed young.
