### ISSUE TITLE
Settings won't save

### ISSUE THREAD

**Issue by SeanRamey** [NovaSquirrel/Mesen-SX#40]
Is there going to be a fix for saving settings and control bindings? This is the only reason I won't use this emulator, is because I can't set up the controller bindings. Last I heard this was an issue caused by Mono 6.12, but has anybody looked into it to make sure that Mono didn't just fix a bug and that actually caused code to break because it was being done wrong, because it's been quite a while, and I would think that if Mono broke everybody's code, it would get fixed pretty quickly.

Also, are there any plans to create an AUR package?

**Comment by NovaSquirrel** [comment]
I'm not aware of anyone trying to debug this and figure out what's going on, and find out if it would be easy to fix or not. It also looks like Mono hasn't had a release since then, aside from a security fix, and I'm under the impression that its Windows Forms support wasn't a very big focus?

I don't have any plans to create an AUR package myself, and don't know what's involved in doing that.

**Comment by NovaSquirrel** [comment]
I ended up naming it X/SX because "Community Edition" usually means "this is the open source version of a paid product" which is not the case here. And there's precedent with FCEUX.
